sphinxcontrib/rst2myst/builders/myst.py
tests/test_build.py
tests/test_build/test_basic.myst
tests/test_build/test_docutils.myst

from `.myst` to `.md` to take advantage of automatic highlighters for `markdown` in editors

migrate to use .md as the extension

---

.gitignore
sphinxcontrib/rst2myst/__init__.py
sphinxcontrib/rst2myst/transform/__init__.py
sphinxcontrib/rst2myst/writers/myst.py
sphinxcontrib/rst2myst/writers/translator.py
sphinxcontrib/rst2myst/writers/writer.py
tests/test_build/test_basic.myst
tests/test_build/test_docutils.myst

This PR adds support for writing `toctree` directives provided by sphinx. 
As part of this PR a transform is added to save the `document` prior to `transforms` and `post_transforms`. This document has then passed to the translator which enables access to `toctree` nodes. However we will have to revisit other methods given we now have more direct access to the underlying RST.

[toctree] add work on supporting toctree

---

sphinxcontrib/rst2myst/builders/myst.py
sphinxcontrib/rst2myst/writers/accumulators.py

PR implements : 
The update of `conf.py` is done using a simple string check for keywords. 
But I was hoping I would be able to load the file as a pickle or a module and add `myst_parser` to the `extensions` object directly. But the file is throwing error on pickling. And module editing is not working.
fixes https://github.com/mmcky/sphinxcontrib-rst2myst/issues/27

[ENH] enable the transfer of build infrastructure into `_build/myst` for buildable output

---

sphinxcontrib/tomyst/writers/myst.py
sphinxcontrib/tomyst/writers/translator.py
tests/source/docutils/directives.rst
tests/test_build/test_docutils.myst

This adds support for migrating `contents` directives provided by `docutils`
```rst
.. contents::
```
all specified directive options are migrated from the pre-transform `pending` node.
https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents

[ENH] add support for parsing docutils contents directives

---

.github/workflows/ci.yml
sphinxcontrib/tomyst/writers/translator.py
tests/snippet.py
tests/snippet/test_snippet.myst
tests/source/snippet/snippet.rst

This add a `skipnode` operation for `system messages` to prevent text from entering output. These system messages are no longer handled as we intercept the `AST` prior to `transforms/post-transforms`

[FIX] fix to skip system message text in output

---

docs/source/config.rst
sphinxcontrib/tomyst/__init__.py
sphinxcontrib/tomyst/writers/myst.py
sphinxcontrib/tomyst/writers/translator.py
tests/source/jupytext-header/conf.py
tests/test_build/test_jupytext.myst

This PR adds improvements to `jupytext` targeting by enabling a context switch in some syntax such as ``code-block`` becomes ``code-cell``. It also adds a default `python` setup for `jupytext` headers

[ENH] improve jupytext targeting

---

sphinxcontrib/tomyst/__init__.py
tests/test_build/test_jupytext.myst

Adjust default `jupytext` header configuration

[FIX] remove line causing issues with jupytext=1.6

---

sphinxcontrib/tomyst/__init__.py
sphinxcontrib/tomyst/writers/translator.py

Show `logger.info` calls when `tomyst_debug = True` in `conf.py`

[ENH] add debug setting to show logger.info

---

sphinxcontrib/tomyst/writers/translator.py
tests/snippet/test_snippet.myst
tests/source/code-blocks-jupytext/test.rst
tests/source/snippet/conf.py
tests/source/snippet/snippet.rst
tests/test_build/test_multi_language_jupytext.myst
tests/test_build/test_multi_language_jupytext.xml

A code block that uses `:class: skip-test` when targeting `jupytext` will now add `tags: [raises-exception]` to `code-cells`
https://myst-nb.readthedocs.io/en/latest/use/execute.html#dealing-with-code-that-raises-errors

[ENH] add support for skip-test for jupytext targeting

---

codecov.yml
sphinxcontrib/tomyst/writers/translator.py
tests/snippet/test_snippet.myst
tests/source/code-blocks-jupytext/test.rst
tests/source/snippet/snippet.rst
tests/test_build/test_multi_language_jupytext.myst
tests/test_build/test_multi_language_jupytext.xml

This PR adds support for `hide-output` specified in `.. code-block::` class attributes. 
```rst
.. code-block::
:class: hide-output
<code>
```
will become
````md
```{code-cell} 
---
tags: [hide-output]
---
<code>
```
````
for `target_jupytext` option.

[ENH] add support for hide-output tags 

---

sphinxcontrib/tomyst/writers/myst.py
sphinxcontrib/tomyst/writers/translator.py
tests/snippet/test_snippet.myst
tests/source/sphinx/conf.py
tests/source/sphinx/directives.rst
tests/source/sphinx/index.rst
tests/test_mystparser.py
tests/test_mystparser/test_sphinx.myst
tests/test_mystparser/test_sphinx.xml

This PR adds support to transfer `only` directives in source `RST`
```rst
.. only:: html
<html>
```
get's transferred to
````md
```{only} html
<html>
```
````

[ENH] add support for only directives (sphinx)

---

.github/workflows/ci.yml
sphinxcontrib/tomyst/writers/myst.py
sphinxcontrib/tomyst/writers/translator.py
tests/snippet/test_snippet.myst
tests/source/docutils/footnotes.rst
tests/source/docutils/index.rst
tests/test_mystparser.py
tests/test_mystparser/test_docutils.myst

This PR updates implementation for footnote references to `myst` syntax
It includes:
1. named footnotes
2. auto-numbered footnotes
https://jupyterbook.org/content/content-blocks.html?highlight=footnote#footnotes

[ENH] fix footnote references

---

sphinxcontrib/tomyst/writers/translator.py
tests/source/docutils/elements.rst
tests/test_mystparser/test_docutils.myst
tests/test_mystparser/test_docutils.xml

This PR fixes an issue when parsing `targets` in documents. This supports the inclusion of
```rst
.. _targetname:
```
and will become
```md
(targetname)=
```

[FIX] fix issue with parsing targets in documents

---

docs/source/index.rst
sphinx_tomyst/writers/translator.py
tests/source/sphinx/directives.rst
tests/test_mystparser/test_docutils.myst
tests/test_mystparser/test_sphinx.myst
tests/test_mystparser/test_sphinx.xml

This improves compatibility with current `myst` parser. If a single `index` entry is used in `rst` then it will return the option on the top line of the directive. 
```rst
.. index::
single: Python
```
will become:
````
```{index} single: Python
```
````
while multioption `index` elements 
```rst
.. index::
single: Python; Runtime
single: Julia
```
will still be included as (which is [currently unsupported](https://github.com/executablebooks/meta/discussions/155)):
````
```{index}
single: Python; Runtime
single: Julia
```
````

[ENH] update index with shorthand index if only one entry

---

sphinx_tomyst/writers/translator.py
tests/source/sphinx/index.rst
tests/source/sphinx/roles.rst
tests/test_mystparser.py
tests/test_mystparser/test_docutils.myst
tests/test_mystparser/test_sphinx.myst

This PR adds support for the `:index:` role.
The following:
```rst
:index:`Julia <single: Julia>`
```
is added as
```md
{index}`Julia <single: Julia>`
```

[ENH] add support for parsing of index roles

---

setup.py
sphinx_tomyst/writers/sphinxcontrib_bibtex.py
sphinx_tomyst/writers/translator.py
tests/source/sphinxcontrib-bibtex/_static/testing.bib
tests/source/sphinxcontrib-bibtex/conf.py
tests/source/sphinxcontrib-bibtex/index.rst
tests/source/sphinxcontrib-bibtex/references.rst
tests/source/sphinxcontrib-bibtex/test.rst
tests/test_sphinxcontrib_bibtex.py
tests/test_sphinxcontrib_bibtex/test_sphinxcontrib_bibtex.myst
tests/test_sphinxcontrib_bibtex/test_sphinxcontrib_bibtex.xml

This adds translator support for setting up `:cite:` and `.. bibliography::` directive supported by `sphinxcontrib-bibtex` to myst roles and directives. 
**Not Supported:**
The following items aren't passed through:
1. `:cited:`
2. `:all:`
3. `:notcited:`, and
4. `:filter:`
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#filtering
as parsing the information from `bib_cache.filter_` hasn't been included in this PR which is contained in an `ast` structure. 
The `:cited:` option will therefore be the effective `default` for all translations.

[ENH] add support for citation references and bibliographies

---

sphinx_tomyst/writers/translator.py
tests/source/docutils/elements.rst
tests/test_mystparser/test_docutils.myst
tests/test_mystparser/test_docutils.xml

This PR fixes nested math in `block_quotes`
It can now parse block quotes such as
```
Let's listen to Wald longer:
As a basis for choosing among critical regions the following
considerations have been advanced by Neyman and Pearson: In accepting
or rejecting :math:`H_0` we may commit errors of two kinds. We commit
an error of the first kind if we reject :math:`H_0` when it is true;
we commit an error of the second kind if we accept :math:`H_0` when
:math:`H_1` is true. 
```
without adding `>` syntax to internal math components.

[block_quote] fix nested math in blockquote context

---

sphinx_tomyst/writers/translator.py

This fixes an introduced bug where whitespace from equations wasn't getting stripped on the `left`

[FIX] fix bug with equations and strip whitespace either side

---

sphinx_tomyst/writers/translator.py
tests/test_mystparser/test_docutils.myst

This PR changes how `block_quotes` are parsed (in addition to fixing List and Table accumulators for various types such as `strong` and `emphasis` nodes). The translator now accumulates block_quote items and then adds `>` syntax in `depart_block_quote`

[ENH] new implementation for block_quote via accumulator

---

sphinx_tomyst/writers/translator.py

This PR adds an informative warning for documents that contain `transition` elements as the information isn't passed through to `markdown`
This applies to transitions added by:
```rst
----
```
https://docutils.sourceforge.io/docs/ref/doctree.html#transition

[WARN] add warning when visiting transition nodes

---

sphinx_tomyst/writers/translator.py

This adds support for saving citation references to `list`, table`, and `block_quote` items

ENL add list and table support for citation_references

---

sphinx_tomyst/writers/translator.py
tests/source/sphinx/_static/test.py
tests/source/sphinx/_static/test.txt
tests/source/sphinx/directives.rst
tests/test_mystparser/test_sphinx.myst
tests/test_mystparser/test_sphinx.xml

This PR adds support for the direct transfer of `.. literalinclude::` markup and skips adding the `content`
**Note:** not all of the options are currently supported
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html?highlight=literalinclude#directive-literalinclude

ENH: add support for literalinclude transfer

---

sphinx_tomyst/writers/translator.py
tests/source/mystnb-code-blocks/test.rst
tests/test_mystnb/test_code_blocks.myst
tests/test_mystnb/test_code_blocks.xml

This PR adds support for `:class: collapse` and passes through to myst using `tags: ["output_scroll"]`
https://jupyterbook.org/content/layout.html#scrolling-cell-outputs

ENH: add support for collapse class -> output_scroll tags in jupyter-book

---

sphinx_tomyst/writers/translator.py

This PR fixes a bug with not capturing trailing syntax for `citation_reference` when nested in lists, tables, block-quotes.

FIX: fix trailing syntax issue for citation_reference

---

sphinx_tomyst/writers/translator.py

This PR adds support for `exercise` and `exerciselist` nodes used in [sphinxcontrib-jupyter](https://github.com/quantecon/sphinxcontrib-jupyter) by some projects

ENH: add support for sphinxcontrib-jupyter.exercise and exerciselist

---

sphinx_tomyst/writers/translator.py

Users of `RST` of make lists that are technical wrapped inside of a `block_quote` due to incorrect use of white space. This PR improves compatibility with these issues by ignoring `block_quote` syntax when inside of a List.

ENH: improve sensitivity to whitespace in RST lists

---

sphinx_tomyst/writers/translator.py

This PR updates the `{doc}` role to use the `document` title from the `environment`

ENH: update doc roles to use document title from the environment

---

sphinx_tomyst/writers/translator.py

This fixes a bug in #100 that was merged too early to add a document name when no text is specified in the `{doc}` role

Fix: Add document name when no {doc} text is provided
